name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g., v0.1.0)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
          persist-credentials: false


      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.PAT_FOR_TAG_PUSH }}@github.com/${{ github.repository }}
      - name: Create and push tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin main
          git push origin ${{ github.event.inputs.version }}
