name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run unit tests
      run: go test -v ./internal/...
    
    - name: Build application
      run: go build -v ./...

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Install spemu
      run: go install github.com/nu0ma/spemu@latest
    
    - name: Start Spanner Emulator
      run: |
        docker run -d --name spanner-emulator \
          -p 9010:9010 -p 9020:9020 \
          gcr.io/cloud-spanner-emulator/emulator:1.5.6
        echo "Waiting for Spanner emulator to be ready..."
        timeout 60 bash -c 'until nc -z localhost 9010; do sleep 1; done'
        echo "Spanner emulator is ready!"
    
    - name: Initialize schema with spemu
      env:
        SPANNER_EMULATOR_HOST: localhost:9010
      run: |
        echo "Initializing database schema..."
        spemu --project test-project --instance test-instance --database test-database --init-schema testdata/schema.sql --verbose
    
    - name: Load test data with spemu
      env:
        SPANNER_EMULATOR_HOST: localhost:9010
      run: |
        echo "Loading test data..."
        spemu --project test-project --instance test-instance --database test-database testdata/seed.sql --verbose
    
    - name: Run integration tests
      env:
        SPANNER_EMULATOR_HOST: localhost:9010
      run: |
        go test -v -tags=integration ./integration_test.go
    
    - name: Cleanup
      if: always()
      run: |
        docker stop spanner-emulator || true
        docker rm spanner-emulator || true